 export const restaurants = [
  {
    id: 1,
    image: "https://picsum.photos/200?random=1",
    name: "Spice Villa",
    cuisines: ["Indian", "Chinese", "Tandoori"],
    rating: 4.3,
    deliveryTime: "30-35 mins",
  },
  {
    id: 2,
    image: "https://picsum.photos/200?random=2",
    name: "Urban Bites",
    cuisines: ["Continental", "Italian", "Cafe"],
    rating: 4.6,
    deliveryTime: "25-30 mins",
  },
  {
    id: 3,
    image: "https://picsum.photos/200?random=3",
    name: "The Hungry Panda",
    cuisines: ["Asian", "Thai", "Chinese"],
    rating: 4.1,
    deliveryTime: "35-40 mins",
  },
  {
    id: 4,
    image: "https://picsum.photos/200?random=4",
    name: "Grill & Chill",
    cuisines: ["Barbecue", "American", "Steakhouse"],
    rating: 4.7,
    deliveryTime: "40-45 mins",
  },
  {
    id: 5,
    image: "https://picsum.photos/200?random=5",
    name: "Desi Rasoi",
    cuisines: ["North Indian", "Mughlai", "Biryani"],
    rating: 4.4,
    deliveryTime: "20-25 mins",
  },
  {
    id: 6,
    image: "https://picsum.photos/200?random=6",
    name: "The Pizza Hub",
    cuisines: ["Italian", "Fast Food", "Snacks"],
    rating: 4.2,
    deliveryTime: "25-30 mins",
  },
  {
    id: 7,
    image: "https://picsum.photos/200?random=7",
    name: "Green Bowl",
    cuisines: ["Healthy", "Salads", "Juices"],
    rating: 4.5,
    deliveryTime: "15-20 mins",
  },
  {
    id: 8,
    image: "https://picsum.photos/200?random=8",
    name: "Royal Feast",
    cuisines: ["Hyderabadi", "Biryani", "South Indian"],
    rating: 4.3,
    deliveryTime: "30-35 mins",
  },
  {
    id: 9,
    image: "https://picsum.photos/200?random=9",
    name: "Ocean Treat",
    cuisines: ["Seafood", "Continental", "Asian"],
    rating: 4.0,
    deliveryTime: "35-40 mins",
  },
  {
    id: 10,
    image: "https://picsum.photos/200?random=10",
    name: "Burger Barn",
    cuisines: ["American", "Fast Food", "Snacks"],
    rating: 4.2,
    deliveryTime: "20-25 mins",
  },
  {
    id: 11,
    image: "https://picsum.photos/200?random=11",
    name: "Curry Junction",
    cuisines: ["Indian", "Punjabi", "Rajasthani"],
    rating: 4.5,
    deliveryTime: "25-30 mins",
  },
  {
    id: 12,
    image: "https://picsum.photos/200?random=12",
    name: "Sweet Cravings",
    cuisines: ["Desserts", "Bakery", "Cafe"],
    rating: 4.6,
    deliveryTime: "15-20 mins",
  },
  {
    id: 13,
    image: "https://picsum.photos/200?random=13",
    name: "Wok Street",
    cuisines: ["Chinese", "Asian", "Japanese"],
    rating: 4.4,
    deliveryTime: "30-35 mins",
  },
  {
    id: 14,
    image: "https://picsum.photos/200?random=14",
    name: "Tandoor Tales",
    cuisines: ["North Indian", "Mughlai", "Kebabs"],
    rating: 4.3,
    deliveryTime: "25-30 mins",
  },
  {
    id: 15,
    image: "https://picsum.photos/200?random=15",
    name: "Café Mocha",
    cuisines: ["Cafe", "Coffee", "Bakery"],
    rating: 4.7,
    deliveryTime: "15-20 mins",
  },
];
